### ISSUE TITLE
Determine is there a loop in linked list

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#12]
A linked list with a loop (or circle) contains a circularly linked list. For a normal linked list, its tail's next points to `null` while for linked list with loop, its tail's next pointer points to another node in the list. e.g.

`a -> b -> c -> d -> f -> c` where two `c` are the same node.

This example list has a loop: `c -> d -> f ->c`, which we want to find out.

Write a function on `MyLinkedList` to determine is there a loop or not.

**Comment by shuangyushan** [comment]
finished
