### ISSUE TITLE
Define MyStack interface

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#13]
A stack is a commonly used data structure with only two operations on it.

1. `push`: add a element to a stack
2. `pop`: get the last pushed element from stack

A stack implements first-in-last-out (FILO or LIFO) mechanism with operations push and pop.

The interface on stack provides only these two operations:
```java
public interface MyStack {
    void push(String element);
    String pop(); // return null if no elements
}
```

Assuming that element type is `String` to simplify the implementation.

**Comment by shuangyushan** [comment]
finished
