### ISSUE TITLE
Implement MyDoubleLinkedList on MyList interface

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#3]
A double linked list extends linked list with an extra link on each node of list which points to previous node. The cost of this extra link is adding space requirement and doubling the time of insertion and deletion because there are more pointers to fix.

Define MyDoubleLinkedList whose node contains both previous and next reference. The previous reference of head node is null, the next reference of the tail node is null.

Doube linked list's node structure extends linked list's by adding a new reference to previous. e.g.
```java
public class MyDoubleNode extends MyNode {
    protected MyNode prev;
    // ...
    // getter and setter omitted
}
```

Data structure for double linked list is the same as linked list's.

**Comment by shuangyushan** [comment]
finished
