### ISSUE TITLE
Implement MyCircularlyLinkedList on MyList interface

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#4]
Make a linked list circular eliminates the "head" and "tail" conceptually, because the tail node's next pointer points to the head. Which node is the head no longer matters.

**Comment by shuangyushan** [comment]
don't know how to write

**Comment by deathspeeder** [comment]
Turn a normal `MyLinkedList` into a circularly linked one just connect list's tail's next to head. e.g. for normal list we have
`a -> b -> c -> null`

A circular version list can be
`a -> b -> c -> a` where two `a` are the same node.

**Comment by shuangyushan** [comment]
finished
