### ISSUE TITLE
Define iterator on MyList and implement on all lists

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#5]
An iterator provides a way to iterate a list based on list implementations. Define an iterator as following,

- Define class `Iterator` with methos:
    - `boolean hasNext()` return `false` if there's no more element to iterate, `true` otherwise
    - `void next()` return the next iterator which representing the next element
    - `String get()` return the element represented by this iterator
- On interface `MyList`  define a method `Iterator iterator()` which returns the first element of the list
- Implement method `iterator` on all lists

**Comment by shuangyushan** [comment]
finished
