### ISSUE TITLE
Merge two sorted lists into a new one

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#6]
Define a class named `ListAlgorithms` which holds some commonly used algorithms related to list.

In class `ListAlgorithms` define a method `MyList mergeSorted(MyList a, MyList b)` witch merges two sorted list, returning the result as an instance of `MyLinkedList`.

_Note: use `iterator` to help merging lists_

**Comment by shuangyushan** [comment]
finished
