### ISSUE TITLE
Change bad names

### ISSUE THREAD

**Issue by deathspeeder** [shuangyushan/JavaProject#8]
On commit https://github.com/shuangyushan/JavaProject/commit/9dbe19176d530e37d06cdf48a7ddc77795d99ed0 change the following names:
- `MyArrayList` change to `MyList`
- `public class MyArrayListImpl implements MyArrayList` change to `public class MyArrayList implements MyList`
- `MyArrayListImplTest` change to `MyArrayListTest`
- `public void deleteLastEle();` change to `public void deleteLast();`
- `public String getElem(int i) throws ArrayIndexOutOfBoundsException;` change to `public String get(int index) throws ArrayIndexOutOfBoundsException;`

**Comment by shuangyushan** [comment]
finished
